// frontend-angular/src/app/components/agent-badge/agent-badge.component.ts
import { Component, Input } from '@angular/core'
import { CommonModule } from '@angular/common'
import { MatChipsModule } from '@angular/material/chips'

const AGENT_META: Record<string, { label: string; bg: string; color: string; icon: string }> = {
  search:      { label: 'Search',      bg: '#DBEAFE', color: '#1E40AF', icon: '🔍' },
  policy:      { label: 'Policy',      bg: '#FEF3C7', color: '#92400E', icon: '📋' },
  destination: { label: 'Destination', bg: '#D1FAE5', color: '#065F46', icon: '🌍' },
  booking:     { label: 'Booking',     bg: '#EDE9FE', color: '#5B21B6', icon: '🎫' },
  judge:       { label: 'Eval',        bg: '#FEE2E2', color: '#991B1B', icon: '⚖' },
}
const FALLBACK = { label: 'Agent', bg: '#F1F5F9', color: '#475569', icon: '🤖' }

@Component({
  selector: 'nva-agent-badge',
  standalone: true,
  imports: [CommonModule, MatChipsModule],
  template: `
    <mat-chip class="nva-chip"
      [style.background]="meta.bg"
      [style.color]="meta.color"
      [style.border-color]="meta.color + '30'">
      {{ meta.icon }} {{ meta.label }}
    </mat-chip>
  `,
})
export class AgentBadgeComponent {
  @Input() agent = ''
  get meta() {
    return AGENT_META[this.agent] ?? { ...FALLBACK, label: this.agent || 'Agent' }
  }
}

// frontend/src/components/Chat/AgentBadge.tsx
import type { AgentType } from '@/types/nva'

const AGENT_CONFIG: Record<AgentType, { label: string; color: string; bg: string }> = {
  search:      { label: 'Search',      color: '#1D4ED8', bg: '#DBEAFE' },
  policy:      { label: 'Policy',      color: '#92400E', bg: '#FEF3C7' },
  destination: { label: 'Destination', color: '#065F46', bg: '#D1FAE5' },
  booking:     { label: 'Booking',     color: '#5B21B6', bg: '#EDE9FE' },
  judge:       { label: 'Judge',       color: '#6B7280', bg: '#F3F4F6' },
}

interface AgentBadgeProps {
  agent: AgentType
}

export default function AgentBadge({ agent }: AgentBadgeProps) {
  const cfg = AGENT_CONFIG[agent] ?? { label: agent, color: '#374151', bg: '#F3F4F6' }
  return (
    <span
      className="inline-flex items-center text-xs font-medium px-2 py-0.5"
      style={{ color: cfg.color, background: cfg.bg, border: `1px solid ${cfg.color}22` }}
    >
      {cfg.label}
    </span>
  )
}
