// frontend/src/components/admin/EvalMetricsTab.tsx
import { useEffect, useMemo, useState } from 'react'
import { getEvalScores } from '@/services/admin'

interface EvalScore {
  eval_id: string
  conversation_id: string
  scores: Record<string, number>
  total_score: number
  passed: boolean
  reasoning: string
  model: string
  timestamp: string
}

const CRITERIA = ['relevance', 'accuracy', 'policy_compliance', 'completeness', 'tone'] as const
type Criterion = typeof CRITERIA[number]

const CRITERION_LABELS: Record<Criterion, string> = {
  relevance:         'Relevance',
  accuracy:          'Accuracy',
  policy_compliance: 'Policy Compliance',
  completeness:      'Completeness',
  tone:              'Tone',
}

function avg(evals: EvalScore[], key: Criterion): number {
  if (!evals.length) return 0
  return evals.reduce((s, e) => s + (e.scores[key] ?? 0), 0) / evals.length
}

function fmtScore(n: number): string {
  return (n * 100).toFixed(1) + '%'
}

function fmtTs(iso: string): string {
  try { return new Date(iso).toLocaleString() } catch { return iso }
}

function scoreColor(n: number): string {
  if (n >= 0.85) return '#065F46'
  if (n >= 0.70) return '#92400E'
  return '#991B1B'
}

function scoreBg(n: number): string {
  if (n >= 0.85) return '#D1FAE5'
  if (n >= 0.70) return '#FEF3C7'
  return '#FEE2E2'
}

export default function EvalMetricsTab() {
  const [evals, setEvals] = useState<EvalScore[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError]   = useState('')
  const [expanded, setExpanded] = useState<string | null>(null)

  useEffect(() => {
    getEvalScores(200)
      .then((data) => setEvals(data as EvalScore[]))
      .catch(() => setError('Failed to load eval scores.'))
      .finally(() => setLoading(false))
  }, [])

  const totalEvals   = evals.length
  const passed       = evals.filter((e) => e.passed).length
  const failed       = totalEvals - passed
  const passRate     = totalEvals ? passed / totalEvals : 0
  const avgTotal     = totalEvals ? evals.reduce((s, e) => s + e.total_score, 0) / totalEvals : 0
  const criteriaAvgs = useMemo(
    () => CRITERIA.map((c) => ({ criterion: c, value: avg(evals, c) })),
    [evals],
  )

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full text-xs" style={{ color: 'var(--text-muted)' }}>
        Loading eval metrics…
      </div>
    )
  }

  if (error) {
    return (
      <div className="flex items-center justify-center h-full text-xs" style={{ color: '#991B1B' }}>
        {error}
      </div>
    )
  }

  return (
    <div className="flex flex-col gap-5 h-full overflow-auto">

      {/* KPI row */}
      <div className="grid gap-3" style={{ gridTemplateColumns: 'repeat(4, 1fr)' }}>
        <KpiCard label="Avg Score" value={fmtScore(avgTotal)} color={scoreColor(avgTotal)} />
        <KpiCard label="Pass Rate" value={fmtScore(passRate)} color={scoreColor(passRate)} />
        <KpiCard label="Total Evals" value={String(totalEvals)} color="var(--navy)" />
        <KpiCard label="Below Threshold" value={String(failed)} color={failed > 0 ? '#991B1B' : '#065F46'} />
      </div>

      {/* Criteria breakdown */}
      {totalEvals > 0 && (
        <div className="flex flex-col gap-2">
          <h3 className="text-xs font-semibold uppercase tracking-wide" style={{ color: 'var(--navy)' }}>
            Avg Score by Criterion
          </h3>
          <div
            className="flex flex-col gap-2 p-4"
            style={{ border: '1px solid var(--border)', boxShadow: '0 1px 3px rgba(0,0,0,0.06)' }}
          >
            {criteriaAvgs.map(({ criterion, value }) => (
              <div key={criterion} className="flex items-center gap-3">
                <span
                  className="text-xs font-medium"
                  style={{ width: 140, flexShrink: 0, color: 'var(--text-muted)' }}
                >
                  {CRITERION_LABELS[criterion]}
                </span>
                <div
                  className="flex-1 relative"
                  style={{ height: 14, background: 'var(--surface)', border: '1px solid var(--border)' }}
                >
                  <div
                    style={{
                      height: '100%',
                      width: `${value * 100}%`,
                      background: scoreColor(value),
                      transition: 'width 0.4s ease',
                    }}
                  />
                </div>
                <span
                  className="text-xs font-mono font-semibold"
                  style={{ width: 44, textAlign: 'right', color: scoreColor(value) }}
                >
                  {fmtScore(value)}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Recent eval list */}
      <div className="flex flex-col gap-2 flex-1">
        <h3 className="text-xs font-semibold uppercase tracking-wide" style={{ color: 'var(--navy)' }}>
          Recent Evaluations
        </h3>
        {evals.length === 0 ? (
          <div className="flex items-center justify-center py-12 text-xs" style={{ color: 'var(--text-muted)' }}>
            No evaluations yet — JudgeAgent runs after each completed conversation turn.
          </div>
        ) : (
          <div style={{ border: '1px solid var(--border)', overflowY: 'auto', maxHeight: 320 }}>
            <table className="w-full text-xs border-collapse">
              <thead>
                <tr style={{ background: 'var(--navy)', color: '#fff', position: 'sticky', top: 0 }}>
                  {['Timestamp', 'Conversation', 'Score', 'Status', 'Model', ''].map((h) => (
                    <th key={h} className="text-left px-3 py-2 font-semibold" style={{ whiteSpace: 'nowrap' }}>
                      {h}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {evals.map((e, i) => {
                  const open = expanded === e.eval_id
                  return (
                    <>
                      <tr
                        key={e.eval_id}
                        style={{
                          background: i % 2 === 0 ? '#fff' : 'var(--surface)',
                          borderBottom: open ? 'none' : '1px solid var(--border)',
                          cursor: 'pointer',
                        }}
                        onClick={() => setExpanded(open ? null : e.eval_id)}
                      >
                        <td className="px-3 py-1.5" style={{ whiteSpace: 'nowrap' }}>{fmtTs(e.timestamp)}</td>
                        <td
                          className="px-3 py-1.5 font-mono"
                          style={{ maxWidth: 140, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}
                          title={e.conversation_id}
                        >
                          {e.conversation_id.slice(0, 8)}…
                        </td>
                        <td className="px-3 py-1.5">
                          <span
                            className="px-2 py-0.5 font-mono font-semibold"
                            style={{
                              background: scoreBg(e.total_score),
                              color: scoreColor(e.total_score),
                            }}
                          >
                            {fmtScore(e.total_score)}
                          </span>
                        </td>
                        <td className="px-3 py-1.5">
                          <span
                            className="px-2 py-0.5 text-xs font-semibold"
                            style={{
                              background: e.passed ? '#D1FAE5' : '#FEE2E2',
                              color: e.passed ? '#065F46' : '#991B1B',
                            }}
                          >
                            {e.passed ? 'PASS' : 'FAIL'}
                          </span>
                        </td>
                        <td className="px-3 py-1.5 font-mono" style={{ color: 'var(--text-muted)' }}>
                          {e.model ?? '—'}
                        </td>
                        <td className="px-3 py-1.5 text-center" style={{ color: 'var(--text-muted)' }}>
                          {open ? '▲' : '▼'}
                        </td>
                      </tr>

                      {/* Expandable drawer */}
                      {open && (
                        <tr
                          key={`${e.eval_id}-drawer`}
                          style={{
                            background: i % 2 === 0 ? '#fff' : 'var(--surface)',
                            borderBottom: '1px solid var(--border)',
                          }}
                        >
                          <td colSpan={6} className="px-4 py-3">
                            <div className="flex flex-col gap-2">
                              {/* Per-criteria scores */}
                              <div className="grid gap-1" style={{ gridTemplateColumns: 'repeat(5, 1fr)' }}>
                                {CRITERIA.map((c) => {
                                  const v = e.scores[c] ?? 0
                                  return (
                                    <div key={c} className="flex flex-col items-center gap-1 p-2"
                                      style={{ background: scoreBg(v), border: `1px solid ${scoreColor(v)}22` }}
                                    >
                                      <span className="text-xs" style={{ color: 'var(--text-muted)', fontSize: 10 }}>
                                        {CRITERION_LABELS[c]}
                                      </span>
                                      <span className="text-sm font-bold font-mono" style={{ color: scoreColor(v) }}>
                                        {fmtScore(v)}
                                      </span>
                                    </div>
                                  )
                                })}
                              </div>
                              {/* Reasoning */}
                              {e.reasoning && (
                                <p className="text-xs italic" style={{ color: 'var(--text-muted)' }}>
                                  "{e.reasoning}"
                                </p>
                              )}
                            </div>
                          </td>
                        </tr>
                      )}
                    </>
                  )
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  )
}

function KpiCard({ label, value, color }: { label: string; value: string; color: string }) {
  return (
    <div
      className="flex flex-col gap-1 p-4"
      style={{ border: '1px solid var(--border)', boxShadow: '0 1px 3px rgba(0,0,0,0.08)' }}
    >
      <span className="text-xs font-semibold uppercase tracking-wide" style={{ color: 'var(--text-muted)' }}>
        {label}
      </span>
      <span className="text-2xl font-bold font-mono" style={{ color }}>
        {value}
      </span>
    </div>
  )
}

// frontend-angular/src/app/components/admin/eval-metrics-tab.component.ts
import { Component, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner'
import { AdminService, EvalScore } from '../../services/admin.service'

const CRITERIA = ['relevance', 'accuracy', 'policy_compliance', 'completeness', 'tone'] as const
const CRITERION_LABELS: Record<string, string> = {
  relevance: 'Relevance', accuracy: 'Accuracy', policy_compliance: 'Policy',
  completeness: 'Completeness', tone: 'Tone',
}

@Component({
  selector: 'nva-eval-metrics-tab',
  standalone: true,
  imports: [CommonModule, MatProgressSpinnerModule],
  template: `
    <div style="padding: 8px 0;">
      <h3 style="margin: 0 0 20px; font-size: 15px; font-weight: 700; color: #1E3A5F;">Eval Metrics</h3>

      <div *ngIf="loading" style="display: flex; justify-content: center; padding: 40px;">
        <mat-spinner diameter="32"></mat-spinner>
      </div>

      <div *ngIf="!loading && scores.length === 0" style="text-align: center; padding: 40px; color: #94a3b8;">No eval scores yet.</div>

      <ng-container *ngIf="!loading && scores.length > 0">
        <!-- KPIs -->
        <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin-bottom: 24px;">
          <div *ngFor="let kpi of kpis" style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 14px 16px;">
            <p style="margin: 0; font-size: 11px; font-weight: 600; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em;">{{ kpi.label }}</p>
            <p style="margin: 6px 0 0; font-size: 22px; font-weight: 700;" [style.color]="kpi.color">{{ kpi.value }}</p>
          </div>
        </div>

        <!-- Per-criteria bars -->
        <div style="margin-bottom: 24px;">
          <h4 style="margin: 0 0 10px; font-size: 13px; font-weight: 600; color: #475569;">Avg Score per Criterion</h4>
          <div style="display: flex; flex-direction: column; gap: 8px;">
            <div *ngFor="let c of criteriaStats" style="display: flex; align-items: center; gap: 12px;">
              <span style="font-size: 12px; color: #64748b; width: 110px; flex-shrink: 0;">{{ c.label }}</span>
              <div style="flex: 1; background: #f1f5f9; border-radius: 4px; height: 14px; overflow: hidden;">
                <div [style.width]="(c.avg * 100) + '%'" [style.background]="scoreColor(c.avg)" style="height: 100%; border-radius: 4px;"></div>
              </div>
              <span style="font-size: 12px; font-weight: 700; width: 42px; text-align: right; flex-shrink: 0;" [style.color]="scoreColor(c.avg)">
                {{ (c.avg * 100).toFixed(0) }}%
              </span>
            </div>
          </div>
        </div>

        <!-- Recent scores table -->
        <h4 style="margin: 0 0 10px; font-size: 13px; font-weight: 600; color: #475569;">Recent Evaluations</h4>
        <div style="overflow-x: auto;">
          <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
            <thead>
              <tr style="background: #f8fafc;">
                <th *ngFor="let h of ['Time','Score','Pass','Model','Reasoning']"
                  style="padding: 7px 12px; text-align: left; font-weight: 600; color: #475569; border-bottom: 1px solid #e2e8f0; white-space: nowrap;">{{ h }}</th>
              </tr>
            </thead>
            <tbody>
              <ng-container *ngFor="let e of scores.slice(0, 50)">
                <tr (click)="toggle(e.eval_id)"
                  style="border-bottom: 1px solid #f1f5f9; cursor: pointer;"
                  [style.background]="expanded === e.eval_id ? '#f0f7ff' : ''">
                  <td style="padding: 7px 12px; color: #334155;">{{ fmt(e.timestamp) }}</td>
                  <td style="padding: 7px 12px;"><span style="font-weight: 700;" [style.color]="scoreColor(e.total_score)">{{ (e.total_score * 100).toFixed(0) }}%</span></td>
                  <td style="padding: 7px 12px;"><span style="font-weight: 700;" [style.color]="e.passed ? '#16a34a' : '#dc2626'">{{ e.passed ? '✓' : '✕' }}</span></td>
                  <td style="padding: 7px 12px; font-size: 11px; color: #94a3b8;">{{ e.model }}</td>
                  <td style="padding: 7px 12px; max-width: 200px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-size: 12px; color: #64748b;">{{ e.reasoning }}</td>
                </tr>
                <tr *ngIf="expanded === e.eval_id" style="background: #f8fafc; border-bottom: 1px solid #e2e8f0;">
                  <td colspan="5" style="padding: 10px 14px;">
                    <div style="display: flex; gap: 16px; flex-wrap: wrap;">
                      <span *ngFor="let c of criteria" style="font-size: 12px;">
                        <span style="color: #64748b;">{{ criterionLabel(c) }}: </span>
                        <span style="font-weight: 700;" [style.color]="scoreColor(e.scores[c] ?? 0)">{{ ((e.scores[c] ?? 0) * 100).toFixed(0) }}%</span>
                      </span>
                    </div>
                    <p *ngIf="e.reasoning" style="margin: 8px 0 0; font-size: 12px; color: #475569; line-height: 1.5;">{{ e.reasoning }}</p>
                  </td>
                </tr>
              </ng-container>
            </tbody>
          </table>
        </div>
      </ng-container>
    </div>
  `,
})
export class EvalMetricsTabComponent implements OnInit {
  scores: EvalScore[] = []
  loading = true
  expanded: string | null = null
  criteria = [...CRITERIA]

  get kpis() {
    if (!this.scores.length) return []
    const avg = this.scores.reduce((s, e) => s + e.total_score, 0) / this.scores.length
    const passRate = this.scores.filter(e => e.passed).length / this.scores.length
    return [
      { label: 'Avg Score', value: `${(avg * 100).toFixed(1)}%`, color: this.scoreColor(avg) },
      { label: 'Pass Rate', value: `${(passRate * 100).toFixed(1)}%`, color: this.scoreColor(passRate) },
      { label: 'Evaluations', value: this.scores.length.toString(), color: '#1E3A5F' },
    ]
  }

  get criteriaStats() {
    return CRITERIA.map(c => {
      const vals = this.scores.map(e => e.scores[c] ?? 0)
      const avg = vals.reduce((a, b) => a + b, 0) / (vals.length || 1)
      return { criterion: c, label: CRITERION_LABELS[c], avg }
    })
  }

  constructor(private adminSvc: AdminService) {}

  ngOnInit(): void {
    this.adminSvc.getEvalScores(200).subscribe({
      next: (data) => { this.scores = data; this.loading = false },
      error: () => { this.loading = false },
    })
  }

  fmt(ts: string): string {
    return new Date(ts).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
  }

  scoreColor(s: number): string {
    if (s >= 0.75) return '#16a34a'
    if (s >= 0.5) return '#D97706'
    return '#dc2626'
  }

  criterionLabel(c: string): string { return CRITERION_LABELS[c] ?? c }

  toggle(id: string): void {
    this.expanded = this.expanded === id ? null : id
  }
}
