// frontend-angular/src/app/components/admin/audit-log-tab.component.ts
import { Component, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'
import { FormsModule } from '@angular/forms'
import { MatFormFieldModule } from '@angular/material/form-field'
import { MatInputModule } from '@angular/material/input'
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner'
import { AdminService, AuditEntry } from '../../services/admin.service'

const AGENT_COLORS: Record<string, string> = {
  orchestrator: '#1E3A5F', search: '#1D4ED8', policy: '#92400E',
  destination: '#065F46', booking: '#5B21B6', judge: '#D97706',
}

@Component({
  selector: 'nva-audit-log-tab',
  standalone: true,
  imports: [CommonModule, FormsModule, MatFormFieldModule, MatInputModule, MatProgressSpinnerModule],
  template: `
    <div style="padding: 8px 0;">
      <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px;">
        <h3 style="margin: 0; font-size: 15px; font-weight: 700; color: #1E3A5F;">
          Audit Log <span style="font-weight: 400; color: #64748b; font-size: 13px;">({{ entries.length }} entries)</span>
        </h3>
        <mat-form-field appearance="outline" subscriptSizing="dynamic" style="width: 220px;">
          <mat-label>Filter</mat-label>
          <input matInput [(ngModel)]="search" placeholder="agent, action…" />
        </mat-form-field>
      </div>

      <div *ngIf="loading" style="display: flex; justify-content: center; padding: 40px;">
        <mat-spinner diameter="32"></mat-spinner>
      </div>

      <div *ngIf="!loading && filtered.length === 0" style="text-align: center; padding: 40px; color: #94a3b8;">
        {{ entries.length === 0 ? 'No audit entries yet.' : 'No entries match the filter.' }}
      </div>

      <div *ngIf="!loading && filtered.length > 0" style="overflow-x: auto;">
        <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
          <thead>
            <tr style="background: #f8fafc;">
              <th *ngFor="let h of ['Time','Agent','Action','Latency','User']" style="padding: 8px 12px; text-align: left; font-weight: 600; color: #475569; border-bottom: 1px solid #e2e8f0; white-space: nowrap;">{{ h }}</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let e of filtered" style="border-bottom: 1px solid #f1f5f9;">
              <td style="padding: 7px 12px; color: #334155;">{{ fmt(e.timestamp) }}</td>
              <td style="padding: 7px 12px;">
                <span [style.background]="agentColor(e.agent)" style="display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 700; color: #fff; text-transform: capitalize;">{{ e.agent }}</span>
              </td>
              <td style="padding: 7px 12px; color: #334155; max-width: 220px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">{{ e.action }}</td>
              <td style="padding: 7px 12px; color: #334155;">{{ e.latency_ms != null ? e.latency_ms + 'ms' : '—' }}</td>
              <td style="padding: 7px 12px; color: #94a3b8;">{{ e.user ?? '—' }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  `,
})
export class AuditLogTabComponent implements OnInit {
  entries: AuditEntry[] = []
  loading = true
  search = ''

  get filtered(): AuditEntry[] {
    const q = this.search.toLowerCase()
    if (!q) return this.entries
    return this.entries.filter(e =>
      e.agent.includes(q) || e.action.toLowerCase().includes(q) || (e.user ?? '').toLowerCase().includes(q)
    )
  }

  constructor(private adminSvc: AdminService) {}

  ngOnInit(): void {
    this.adminSvc.getAuditLog(100).subscribe({
      next: (data) => { this.entries = data; this.loading = false },
      error: () => { this.loading = false },
    })
  }

  fmt(ts: string): string {
    return new Date(ts).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
  }

  agentColor(agent: string): string { return AGENT_COLORS[agent] ?? '#374151' }
}

// frontend-spectrum/src/components/admin/AuditLogTab.tsx
import { useEffect, useState } from 'react'
import { ProgressCircle, SearchField } from '@react-spectrum/s2'
import { getAuditLog } from '@/services/admin'
import type { AuditEntry } from '@/services/admin'

const AGENT_COLORS: Record<string, string> = {
  orchestrator: '#1E3A5F', search: '#1D4ED8', policy: '#92400E',
  destination: '#065F46', booking: '#5B21B6', judge: '#D97706',
}

function fmt(ts: string) {
  return new Date(ts).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
}

export default function AuditLogTab() {
  const [entries, setEntries] = useState<AuditEntry[]>([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')

  useEffect(() => {
    getAuditLog(100).then(setEntries).finally(() => setLoading(false))
  }, [])

  const filtered = entries.filter((e) => {
    const q = search.toLowerCase()
    return !q || e.agent.includes(q) || e.action.toLowerCase().includes(q) || (e.user ?? '').toLowerCase().includes(q)
  })

  if (loading) return <div style={center}><ProgressCircle isIndeterminate aria-label="Loading" /></div>

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
        <h3 style={heading}>Audit Log <span style={{ fontWeight: 400, color: '#64748b', fontSize: 13 }}>({entries.length} entries)</span></h3>
        <SearchField label="" aria-label="Search" value={search} onChange={setSearch} placeholder="Filter agent, action…" UNSAFE_style={{ width: 200 }} />
      </div>

      {filtered.length === 0 ? (
        <div style={{ textAlign: 'center', padding: 40, color: '#94a3b8' }}>
          {entries.length === 0 ? 'No audit entries yet.' : 'No entries match the filter.'}
        </div>
      ) : (
        <div style={{ overflowX: 'auto' }}>
          <table style={tbl}>
            <thead>
              <tr style={{ background: '#f8fafc' }}>
                <th style={th}>Time</th>
                <th style={th}>Agent</th>
                <th style={th}>Action</th>
                <th style={th}>Latency</th>
                <th style={th}>User</th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((e, i) => (
                <tr key={e.log_id ?? i} style={{ borderBottom: '1px solid #f1f5f9' }}>
                  <td style={td}>{fmt(e.timestamp)}</td>
                  <td style={td}>
                    <span style={{ ...badge, background: AGENT_COLORS[e.agent] ?? '#374151' }}>
                      {e.agent}
                    </span>
                  </td>
                  <td style={{ ...td, maxWidth: 220, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{e.action}</td>
                  <td style={td}>{e.latency_ms != null ? `${e.latency_ms}ms` : '—'}</td>
                  <td style={{ ...td, color: '#94a3b8' }}>{e.user ?? '—'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}

const center: React.CSSProperties = { display: 'flex', justifyContent: 'center', padding: 40 }
const heading: React.CSSProperties = { margin: 0, fontSize: 15, fontWeight: 700, color: '#1E3A5F' }
const tbl: React.CSSProperties = { width: '100%', borderCollapse: 'collapse', fontSize: 13 }
const th: React.CSSProperties = { padding: '8px 12px', textAlign: 'left', fontWeight: 600, color: '#475569', borderBottom: '1px solid #e2e8f0', whiteSpace: 'nowrap' }
const td: React.CSSProperties = { padding: '7px 12px', color: '#334155', verticalAlign: 'middle' }
const badge: React.CSSProperties = { display: 'inline-block', padding: '2px 8px', borderRadius: 4, fontSize: 11, fontWeight: 700, color: '#fff', textTransform: 'capitalize' }
