// frontend-angular/src/app/components/admin/model-selection-tab.component.ts
import { Component, OnInit, inject } from '@angular/core'
import { CommonModule } from '@angular/common'
import { FormsModule } from '@angular/forms'
import { MatFormFieldModule } from '@angular/material/form-field'
import { MatInputModule } from '@angular/material/input'
import { MatButtonModule } from '@angular/material/button'
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner'
import { MatSnackBar } from '@angular/material/snack-bar'
import { AdminService, AgentConfig } from '../../services/admin.service'

const AGENT_LABELS: Record<string, string> = {
  orchestrator: 'Orchestrator', search: 'Search', policy: 'Policy',
  destination: 'Destination', booking: 'Booking', judge: 'Judge',
}
const AGENT_COLORS: Record<string, string> = {
  orchestrator: '#1E3A5F', search: '#1D4ED8', policy: '#92400E',
  destination: '#065F46', booking: '#5B21B6', judge: '#D97706',
}

@Component({
  selector: 'nva-model-selection-tab',
  standalone: true,
  imports: [CommonModule, FormsModule, MatFormFieldModule, MatInputModule, MatButtonModule, MatProgressSpinnerModule],
  template: `
    <div style="padding: 8px 0;">
      <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px;">
        <h3 style="margin: 0; font-size: 15px; font-weight: 700; color: #1E3A5F;">Model Configuration</h3>
        <button mat-flat-button (click)="save()" [disabled]="saving || loading"
          style="background: #1E3A5F; color: #fff; font-size: 13px;">
          {{ saving ? 'Saving…' : 'Save All' }}
        </button>
      </div>

      <div *ngIf="loading" style="display: flex; justify-content: center; padding: 40px;">
        <mat-spinner diameter="32"></mat-spinner>
      </div>

      <div *ngIf="!loading" style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px;">
        <div *ngFor="let agent of agentKeys" style="border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden;">
          <div [style.background]="agentColor(agent)" style="padding: 8px 12px;">
            <span style="font-weight: 700; font-size: 13px; color: #fff;">{{ agentLabel(agent) }}</span>
          </div>
          <div style="padding: 12px; display: flex; flex-direction: column; gap: 10px;">
            <mat-form-field appearance="outline" style="width: 100%;" subscriptSizing="dynamic">
              <mat-label>Model</mat-label>
              <input matInput [(ngModel)]="configs[agent].model" />
            </mat-form-field>
            <mat-form-field appearance="outline" style="width: 100%;" subscriptSizing="dynamic">
              <mat-label>Temperature</mat-label>
              <input matInput type="number" [(ngModel)]="configs[agent].temperature" min="0" max="2" step="0.1" />
            </mat-form-field>
          </div>
        </div>
      </div>
    </div>
  `,
})
export class ModelSelectionTabComponent implements OnInit {
  configs: Record<string, AgentConfig> = {}
  loading = true
  saving = false

  private snackBar = inject(MatSnackBar)
  get agentKeys(): string[] { return Object.keys(this.configs) }

  constructor(private adminSvc: AdminService) {}

  ngOnInit(): void {
    this.adminSvc.getModelConfig().subscribe({
      next: (data) => { this.configs = data; this.loading = false },
      error: () => {
        this.loading = false
        this.snackBar.open('Failed to load config', 'Dismiss', { duration: 5000 })
      },
    })
  }

  agentLabel(agent: string): string { return AGENT_LABELS[agent] ?? agent }
  agentColor(agent: string): string { return AGENT_COLORS[agent] ?? '#374151' }

  save(): void {
    this.saving = true
    this.adminSvc.saveModelConfig(this.configs).subscribe({
      next: () => {
        this.saving = false
        this.snackBar.open('Configuration saved', undefined, { duration: 3000 })
      },
      error: () => {
        this.saving = false
        this.snackBar.open('Save failed — check console', 'Dismiss', { duration: 5000 })
      },
    })
  }
}

// frontend-spectrum/src/components/admin/ModelSelectionTab.tsx
import { useEffect, useState } from 'react'
import { Button, TextField, NumberField, ProgressCircle, ToastQueue } from '@react-spectrum/s2'
import { getModelConfig, updateModelConfig } from '@/services/admin'
import type { AgentConfig } from '@/services/admin'

const AGENT_LABELS: Record<string, string> = {
  orchestrator: 'Orchestrator',
  search: 'Search',
  policy: 'Policy',
  destination: 'Destination',
  booking: 'Booking',
  judge: 'Judge',
}

export default function ModelSelectionTab() {
  const [config, setConfig] = useState<Record<string, AgentConfig>>({})
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)

  useEffect(() => {
    getModelConfig()
      .then(setConfig)
      .catch(() => ToastQueue.negative('Failed to load config', { timeout: 5000 }))
      .finally(() => setLoading(false))
  }, [])

  function setField(agent: string, field: keyof AgentConfig, value: string | number) {
    setConfig((prev) => ({ ...prev, [agent]: { ...prev[agent], [field]: value } }))
  }

  async function save() {
    setSaving(true)
    try {
      await updateModelConfig(config)
      ToastQueue.positive('Configuration saved', { timeout: 3000 })
    } catch {
      ToastQueue.negative('Save failed — check console', { timeout: 5000 })
    } finally { setSaving(false) }
  }

  if (loading) return <div style={center}><ProgressCircle isIndeterminate aria-label="Loading" /></div>

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
        <h3 style={heading}>Per-Agent LLM Configuration</h3>
        <Button variant="accent" onPress={save} isPending={saving}>Save All</Button>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
        {Object.entries(config).map(([agent, cfg]) => (
          <div key={agent} style={card}>
            <div style={{ ...agentHeader, background: agentColor(agent) }}>
              <span style={{ fontWeight: 700, fontSize: 13, color: '#fff' }}>
                {AGENT_LABELS[agent] ?? agent}
              </span>
            </div>
            <div style={{ padding: '14px 16px', display: 'flex', flexDirection: 'column', gap: 12 }}>
              <TextField
                label="Model"
                value={cfg.model ?? ''}
                onChange={(v) => setField(agent, 'model', v)}
                UNSAFE_style={{ width: '100%' }}
              />
              <NumberField
                label="Temperature"
                value={typeof cfg.temperature === 'number' ? cfg.temperature : 0}
                onChange={(v) => setField(agent, 'temperature', v)}
                minValue={0} maxValue={2} step={0.1}
                formatOptions={{ minimumFractionDigits: 1, maximumFractionDigits: 1 }}
                UNSAFE_style={{ width: '100%' }}
              />
              {cfg.max_tokens != null && (
                <NumberField
                  label="Max Tokens"
                  value={cfg.max_tokens}
                  onChange={(v) => setField(agent, 'max_tokens', v)}
                  minValue={64} maxValue={8192} step={64}
                  UNSAFE_style={{ width: '100%' }}
                />
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

function agentColor(agent: string): string {
  const map: Record<string, string> = {
    orchestrator: '#1E3A5F', search: '#1D4ED8', policy: '#92400E',
    destination: '#065F46', booking: '#5B21B6', judge: '#D97706',
  }
  return map[agent] ?? '#374151'
}

const center: React.CSSProperties = { display: 'flex', justifyContent: 'center', padding: 40 }
const heading: React.CSSProperties = { margin: 0, fontSize: 15, fontWeight: 700, color: '#1E3A5F' }
const card: React.CSSProperties = { border: '1px solid #e2e8f0', borderRadius: 8, overflow: 'hidden', background: '#fff', boxShadow: '0 1px 3px rgba(0,0,0,0.08)' }
const agentHeader: React.CSSProperties = { padding: '8px 14px' }
